# Generated by Django 5.0.1 on 2024-02-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0003_remove_tombstone_birth_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tombstone",
            name="birth_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Год создания"
            ),
        ),
        migrations.AddField(
            model_name="tombstone",
            name="death_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="Год смерти"),
        ),
    ]
