# Generated by Django 5.0.1 on 2024-02-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0004_tombstone_birth_year_tombstone_death_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="link",
            field=models.SlugField(
                blank=True, max_length=200, null=True, verbose_name="Ссылка на компанию"
            ),
        ),
    ]
