# Generated by Django 5.0.1 on 2024-02-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0005_alter_tombstone_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="score_company",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Оценочная стоимость на рынке"
            ),
        ),
        migrations.AlterField(
            model_name="tombstone",
            name="tombstone_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ID надгробия"
            ),
        ),
    ]
