# Generated by Django 5.0.1 on 2024-02-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0007_alter_tombstone_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tombstone",
            name="logo",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="photos/%Y/%m/%d/"
            ),
        ),
    ]
