# Generated by Django 5.0.1 on 2024-02-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0009_alter_tombstone_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="logo",
            field=models.ImageField(
                default=None, upload_to="photos/%Y/%m/%d/", verbose_name="Логотип"
            ),
        ),
    ]
