# Generated by Django 5.0.1 on 2024-02-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0014_alter_tombstone_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads_model")),
            ],
        ),
    ]
