# Generated by Django 5.0.1 on 2024-03-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0015_uploadfiles"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadFiles",
        ),
        migrations.AlterField(
            model_name="tombstone",
            name="alternate_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Альтернативное название",
            ),
        ),
        migrations.AlterField(
            model_name="tombstone",
            name="create_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="tombstone",
            name="logo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="uploads_model",
                verbose_name="Логотип",
            ),
        ),
    ]
