# Generated by Django 5.0.1 on 2024-03-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0016_delete_uploadfiles_alter_tombstone_alternate_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="create_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата создания"),
        ),
    ]
