# Generated by Django 5.0.1 on 2024-03-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0017_alter_tombstone_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="create_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время создания"
            ),
        ),
    ]
