# Generated by Django 5.0.1 on 2024-03-06 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0019_alter_tombstone_birth_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="birth_year",
            field=models.IntegerField(
                default=None,
                validators=[django.core.validators.MaxValueValidator(4)],
                verbose_name="Год создания",
            ),
        ),
        migrations.AlterField(
            model_name="tombstone",
            name="death_year",
            field=models.IntegerField(
                default=None,
                validators=[django.core.validators.MaxValueValidator(4)],
                verbose_name="Год смерти",
            ),
        ),
    ]
