# Generated by Django 5.0.1 on 2024-03-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0021_alter_tombstone_birth_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="logo",
            field=models.ImageField(
                default=None, upload_to="uploads_model", verbose_name="Логотип"
            ),
        ),
    ]
