# Generated by Django 5.0.1 on 2024-03-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0022_alter_tombstone_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="count_employee",
            field=models.IntegerField(
                default=None, verbose_name="Количество сотрудников"
            ),
        ),
        migrations.AlterField(
            model_name="tombstone",
            name="revenue",
            field=models.IntegerField(default=None, verbose_name="Доход компании"),
        ),
        migrations.AlterField(
            model_name="tombstone",
            name="score_company",
            field=models.IntegerField(
                default=None, verbose_name="Оценочная стоимость на рынке"
            ),
        ),
    ]
