# Generated by Django 5.0.1 on 2024-03-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0023_alter_tombstone_count_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="link",
            field=models.SlugField(
                default=None, max_length=200, verbose_name="Ссылка на компанию"
            ),
        ),
    ]
