# Generated by Django 5.0.1 on 2024-03-06 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0024_alter_tombstone_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="link",
            field=models.CharField(
                default=None, max_length=200, verbose_name="Ссылка на компанию"
            ),
        ),
    ]
