# Generated by Django 5.0.1 on 2024-03-08 22:26

import property.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0026_remove_tombstone_id_alter_tombstone_tombstone_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=property.models.get_profile_image_filepath,
            ),
        ),
    ]
