# Generated by Django 5.0.1 on 2024-03-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0029_users_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="username",
            ),
        ),
    ]
