# Generated by Django 5.0.1 on 2024-03-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0030_alter_users_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="Email"
            ),
        ),
    ]
