# Generated by Django 5.0.1 on 2024-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0033_alter_users_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profile_image",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to=""
            ),
        ),
    ]
