# Generated by Django 5.0.1 on 2024-03-09 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0034_alter_users_profile_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
    ]
