# Generated by Django 5.0.1 on 2024-03-09 18:12

import property.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0035_rename_users_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=property.models.get_profile_image_filepath,
            ),
        ),
    ]
