# Generated by Django 5.0.1 on 2024-03-09 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0037_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
