# Generated by Django 5.0.1 on 2024-03-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0039_user_url_alter_user_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="user",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Пользователь"
            ),
        ),
    ]
