# Generated by Django 5.0.1 on 2024-03-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0041_remove_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
