# Generated by Django 5.0.1 on 2024-03-14 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0045_alter_user_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(max_length=500, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время отправки"
                    ),
                ),
                (
                    "tombstone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="property.tombstone",
                        verbose_name="ID надгробия",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="property.user",
                        verbose_name="ID пользователя",
                    ),
                ),
            ],
        ),
    ]
