# Generated by Django 5.0.1 on 2024-03-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0047_alter_tombstone_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="count_employee",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Количество сотрудников",
            ),
        ),
        migrations.AlterField(
            model_name="tombstone",
            name="revenue",
            field=models.IntegerField(
                blank=True, default=None, null=True, verbose_name="Доход компании"
            ),
        ),
        migrations.AlterField(
            model_name="tombstone",
            name="score_company",
            field=models.IntegerField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Оценочная стоимость на рынке",
            ),
        ),
    ]
