# Generated by Django 5.0.1 on 2024-03-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0048_alter_tombstone_count_employee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tombstone",
            name="link",
            field=models.SlugField(
                blank=True,
                default=None,
                max_length=200,
                null=True,
                verbose_name="Ссылка на компанию",
            ),
        ),
    ]
