# Generated by Django 5.0.1 on 2024-03-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0053_alter_tombstone_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tombstone",
            name="people",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Ключевые люди и их роли",
            ),
        ),
    ]
